### PR TITLE
Issue/189/autocompile notebooks

### PR DESCRIPTION
**Pull request by matthewkirby**
This PR addresses the first set of points in Issue #189. 
- [x] Renamed example notebooks for consistency and descriptiveness
- [x] Cleaned up the sphinx settings file
- [x] Adjusted some sphinx settings for slight changes to docs (sidebar expands now and there aren't a bunch of sidebar entries for the same file)
- [x] Removed .rst files for uncompiled notebooks
- [x] Moved some entries in our global `.gitignore` that only pertained to docs into an additional file in docs directory
- [x] Added a new config file for docs. Anyone who needs to add a module or example to documentation only needs to add it there.
- [x] Automate execution of the example notebooks
- [x] Automatically compiled executed notebooks into .rst files
- [x] Made example section in sidebar for the examples
- [x] Removed instructions to manually compile these files from CONTRIBUTING.md
- [x] Adjust the primary heading of each notebook to edit sidebar names. (The first heading is what appears in the sidebar on the docs)
- [x] Small adjustments to example notebooks to be automagically convertible
- [x] Small adjustments to example notebooks to be automagically executable

Finally
- Ensure docs compile with CONVERTED notebooks
    - [x] Locally
    - [x] Travis
    - [x] readthedocs
- Ensure docs compile with CONVERTED and EXECUTED notebooks
    - [x] ~Locally (works but the line is commented out...)~
    - [ ] ~Travis~
    - [ ] ~readthedocs~

### CODE REVIEW

**Comment by cavestruz** [comment]
Just a note, there's another set of to-do points in #189 based on @pbrown801's test go-through the docs.  I think @shenmingfu will start addressing these in a separate branch, since these are all .rst edits at the moment.

**Comment by matthewkirby** [comment]
Thanks for flagging that. Since I have moved and renamed some of the things that compile into the docs, we should make sure that everything that should be there is there when we go to do merges. I don't envision a problem but just in case.

**Comment by matthewkirby** [comment]
Wooooo. Step 1 is done! The notebooks now get converted on travis! Next up, execution.

**Comment by matthewkirby** [comment]
readthedocs link: https://clmm.readthedocs.io/en/issue-189-autocompile-notebooks/

Hopefully the notebooks are converted =X

**Comment by matthewkirby** [comment]
Summary: readthedocs cannot run C code, aka GSL which cluster_toolkit needs. So we cannot run anything there. 

Time for a new solution. But first, I am going to finish having travis execute all of the notebooks because that will at least let us test whether they execute successfully.

**Comment by matthewkirby** [comment]
But wait! GSL is installable with conda and rtd supports building a conda environment. https://anaconda.org/conda-forge/gsl/

We aren't dead yet!

**Comment by cavestruz** [comment]
Oooooh.....

**Comment by matthewkirby** [comment]
The other issue I am runnign into is the pipeline demo notebook was struggling to execute with nbconvert. Then I updated nbconvert and jupyter_client and it was no problem working. 

But I am now getting that same crash on travis.

**Comment by matthewkirby** [comment]
Alright, begin the stream of tiny commits to test read the docs and my conda environment file.

**Comment by matthewkirby** [comment]
Alrighty. This is now ready for review. I opened a new issue for notebook execution as that is not yet working. 

However, I have refactored a good chunk of how the docs are built and added several configuration files for how to build the docs. We also include a conda environment file which can be used to install all of our dependencies that readthedocs uses (if I am not mistaken, this is 99% of the work needed to make a docker container. We might think about this for easy running at nersc?).

**Comment by matthewkirby** [comment]
You can see the documentation at: https://clmm.readthedocs.io/en/issue-189-autocompile-notebooks/

Note that I also fixed the bug that was causing the docstrings to not be compiled on master.

**Comment by matthewkirby** [comment]
Also this is definitely a squash and merge case haha.

The vast majority of commits here are adding a single dependency to a requirement file (i did this for 3-4 different types of requirement files) and pushing to test travis and readthedocs.

**Pull request merged**
