### PR TITLE
add lowercase fix

### PR DESCRIPTION
**Pull request by m-aguena**
From Issue #369

### CODE REVIEW

**Review by combet — COMMENTED** [review]
Thanks @m-aguena - worked like a charm.

Question: should we update the docstrings to reflect the fact that upper case are now permitted?

**Comment by m-aguena** [comment]
@combet that is a good idea

**Comment by m-aguena** [comment]
@combet I removed the case dependence of `error_model` in `compute_radial_averages` and `method` in `make_bins` and added it to the documentation.

**Review by combet — APPROVED** [review]
All good, thanks @m-aguena!

**Pull request merged**
