### PR TITLE
Issue/158/validate physical functions

### PR DESCRIPTION
**Pull request by m-aguena**
Added notebook comparing CLMM output with `NumCosmo`. It can also run with some saved values computed by `NumCosmo` without having to actually run `NumCosmo`.

### CODE REVIEW

**Comment by m-aguena** [comment]
@aimalz I think the name of this issue is what was confusing. It should be code comparison or something like that. The validation tests of the notebook were added in #162 as unit tests.
@matthewkirby pickled file removed.

**Comment by m-aguena** [comment]
> As this stands, I cannot run the notebook. Is this PR deprecated after the other two validation test PRs?

@matthewkirby That's strange, it ran ok for me. What error did you get?

**Comment by matthewkirby** [comment]
@m-aguena Is this PR still relevant? Or is everything that is in this PR now merged to master?

**Comment by cavestruz** [comment]
Hi @m-aguena - is this ready for review now?  Looks like the checks are passing :-)

**Comment by m-aguena** [comment]
I guess this PR is not necessary anymore. Its scope was solved in PR #200.

**Pull request closed without merging**
