### PR TITLE
Issue/209/version

### PR DESCRIPTION
**Pull request by cristobal-sifon**
This PR addresses both points raised in #209

### CODE REVIEW

**Comment by cristobal-sifon** [comment]
will do. Does it make sense though rather than duplicating it, to have ``get_version`` in, say, ``__init__.py``? Any other suggestions?

**Comment by matthewkirby** [comment]
There must be a standard because I expect that others run into this problem.

**Comment by matthewkirby** [comment]
Actually. For docs to compile correctly, the package needs to be installed. Its possible that we can just `import clmm` and then say `clmm.__version__` in the docs config.

**Comment by matthewkirby** [comment]
I just tested this and we can do something like this
```
from clmm import __version__ as clmm_version
version = clmm_version
release = version
```

**Comment by cristobal-sifon** [comment]
OK let me try that

**Comment by matthewkirby** [comment]
Looks great! Merging!

**Pull request merged**
