### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hsinfan1996**
Force NumCosmo=0.15.4 (0.16.0 is the latest)

### CODE REVIEW

**Comment by hsinfan1996** [comment]
We can also relax `'ps_reltol'` in tests/conftest.py to 6e-4 to fix the problem, because all the others tests are not affected by the new version.

**Comment by hsinfan1996** [comment]
Numpy 1.24.0 is now on conda-forge, and it will break Astropy. The Astropy team has pushed a fix, and hopefully there will be a new minor release soon.

**Comment by m-aguena** [comment]
Let's use this patch for now and put a pin for the new astropy version

**Comment by hsinfan1996** [comment]
Sorry, I made it confusing. NumCosmo and Astropy (due to Numpy 1.24.0) are separate issues. Before there is a new minor version for Astropy, we will need to pin NumCosmo=0.15.4 and Numpy=1.23.5.

**Comment by m-aguena** [comment]
@hsinfan1996 how is the build is working without fixing numpy?

**Comment by hsinfan1996** [comment]
> @hsinfan1996 how is the build is working without fixing numpy?

That was the run before Numpy was pushed to conda-forge.

**Comment by m-aguena** [comment]
I see, and a new astropy release will fix this? If it is the case, I say we proceed the way I suggested

**Comment by hsinfan1996** [comment]
> I see, and a new astropy release will fix this? If it is the case, I say we proceed the way I suggested

Yes. Do you mean pinning NumCosmo after Astropy releases a new minor version?

**Comment by m-aguena** [comment]
> > I see, and a new astropy release will fix this? If it is the case, I say we proceed the way I suggested
> 
> Yes. Do you mean pinning NumCosmo after Astropy releases a new minor version?

No, I mean we will be able to unpin the numcosmo and numpy versions after the new astropy mirror, right? We just have to fix them for now

**Comment by hsinfan1996** [comment]
To unpin NumCosmo, we will need to relax the tolerance on power spectrum calculation.

**Comment by m-aguena** [comment]
@hsinfan1996 do you know exactly why the latest version of numcosmo does not pass? Is is an issue on numcosmo or on numpy?

**Review by m-aguena — APPROVED** [review]

**Pull request merged**
