### PR TITLE
Issue/487/update GitHub actions

### PR DESCRIPTION
**Pull request by hsinfan1996**

### CODE REVIEW

**Comment by hsinfan1996** [comment]
Still need to update README regarding the minimum Astropy version.

**Comment by combet** [comment]
@hsinfan1996 - could you comment on why there's a need for `Build and Check Minimum`. Excluding coverage, there is now 4 checks to pass, instead of 2 before. That seems like a lot of redundancy?

**Comment by hsinfan1996** [comment]
> Thanks @hsinfan1996 - could you comment on why there's a need for `Build and Check Minimum`. Excluding coverage, there is now 4 checks to pass, instead of 2 before. Is this absolutely necessary?

There are only two checks actually. Once a pull request is open, any commit will be checked twice since we request checks to be performed on both push and pull request. They are redundant I would say, in the way that we only need checks when a commit is pushed. `Build and Check Minimum` is not absolutely necessary, but since we are adding new functionalities, I thought it would be useful if we could check the minimum requirement stated in the readme to ensure backward compatibility.

**Comment by hsinfan1996** [comment]
Now there are only two checks to run after a pull request is created. We can also make the minimal check significantly faster by installing and testing CCL backend only.

**Comment by m-aguena** [comment]
PR converted to draft as per the new procedure (labels `PR: Ready for Review` and `PR: Not ready` will not be used anymore). Please use the button `Ready for review` if/when this PR is ready.

**Comment by hsinfan1996** [comment]
Checks can complete within ~4 min.

**Review by m-aguena — APPROVED** [review]
I all looks good

**Pull request merged**
