### PR TITLE
Example3 update

### PR DESCRIPTION
**Pull request by shenmingfu**
Issue #464

### CODE REVIEW

**Comment by shenmingfu** [comment]
The applegate14 model has been added and tested in example3. I will add schrabback18 after it's merged into the main.

**Comment by shenmingfu** [comment]
Now the "schrabback18" option (#475) is also added into the notebook.

**Comment by marina-ricci** [comment]
- Header text : Correct typos (e.g. "the Chang. (2013)", "yield a bias mass", " el at."). Modify the sentence " add a model using the method from Applegate el at. (2014)" to explain what method it is (e.g. "method to account for the redshift distribution from Applegate et al.")

**Review by marina-ricci — CHANGES_REQUESTED** [review]
- Header text :
- [x]  Correct typos (e.g. "the Chang. (2013)", "yield a **bias** mass", " **el at.**"). 
- [x] Modify the sentence " add a model using the method from Applegate el at. (2014)" to explain what method it is (e.g. "method to account for the redshift distribution from Applegate et al.")

- Typo in the notebook : 
- [ ] refer to "Chang et al. 2013" and not "the Chang. (2013)", 
- [ ]  "the corresponding model is simply given by **the fucntion** below:"

- [ ] Add comments about accounting for the redshift distribution using the "Applegate" method under the profiles figure.

**Comment by marina-ricci** [comment]
Thank you @shenmingfu for the notebook!
Please when you make a PR add a bit of context and list what you changed, so it is easier to review, without having to dig in the issue's history. Here you changed 2 notebooks, whereas I think you only need to modify "Example3". Another point is that this notebook will have to be updated after PR #465 is merged.

**Comment by shenmingfu** [comment]
Hi @marina-ricci , Thank you for the review. I have adjusted the texts. The previous edits include adding comments to make the text more clear, adding functions to use applegate14 and schrabback18 methods, and adding commands to run those new functions (making shear profiles, fitting masses, and making plots).
I'm not sure why Example4 were also changed. But it looks we can adopt those changes? Since they switch from environment `desc` to `clmm-env`. If not, I can remove those changes.

**Comment by m-aguena** [comment]
PR converted to draft as per the new procedure (labels `PR: Ready for Review` and `PR: Not ready` will not be used anymore). Please use the button `Ready for review` if/when this PR is ready.

**Comment by shenmingfu** [comment]
@marina-ricci Sorry for my delay. I'm planning to use the newly defined functions `compute_beta_s_mean` and `compute_beta_s_square_mean` etc. from the new `clmm/utils.py`. In my current Example3, I defined similar functions and quantities in the notebook, so I will replace them with the ones in `clmm/utils.py`. Do you think that will be the solution? 

However, that will require updating files like `clmm/utils.py` in this branch. Currently, only Example3 is the file that has been changed (the modification of Example 4 can be skipped). Should I modify those files in this branch as well? If so, could you teach me how to do that properly (a lot of files were updated in issue #465 and PR #467)? Otherwise, can we merge this branch first, so those files will be updated, then I adjust the Example 3 in a new branch? 

Thanks.

**Comment by shenmingfu** [comment]
@marina-ricci I have updated the notebook using the updated function `compute_reduced_tangential_shear()`, and now `beta_s_mean` and `beta_s_square_mean` are computed internally; we don't need to provide them in the notebook. The PR is ready for review. While updating the notebook, I noticed a typo in the original definition of beta, so I also updated that.

**Comment by shenmingfu** [comment]
@marina-ricci Thanks for your feedback. The changes in Example4 are the python version and environment. We can skip that.
I have updated `z_distrib_func` in those functions in Example3.
The reduced shear formulae of Applegate14 (https://github.com/LSSTDESC/CLMM/issues/397#issue-900556489) and Schrabback18 (https://github.com/LSSTDESC/CLMM/pull/425#pullrequestreview-793004842) are identical if we skip the Taylor-expansion terms higher than the first order of kappa_inf (i.e. f(beta_s)*(kappa_inf)^n, n>=2). Here we are using the same redshift distribution (the default Chang et al. 2013). So they are close when kappa_inf is small (e.g. when the radial distance is not too small). For the noisy data, the error bars of fitted masses derived from the two methods are slightly different (~0.3%).

**Review by marina-ricci — APPROVED** [review]

**Comment by marina-ricci** [comment]
@shenmingfu looks good to me! I'll merge the PR.

**Comment by shenmingfu** [comment]
@marina-ricci Thank you.

**Pull request merged**
