### PR TITLE
issue/#90/update of the examples

### PR DESCRIPTION
**Pull request by marina-ricci**
I have modified shear_azimuthal_averager_demo.ipynb and data_and_model_demo.ipynb in the examples folder:
 - I have updated the DC2 extragalactic catalog from which the data are extracted to its newer version.
 - I corrected one small bug. 
 - I have made several changes for readability.

### CODE REVIEW

**Comment by matthewkirby** [comment]
So in this branch, we changed the example notebooks to use DC2 data rather than mock catalogs that @combet put together. I think we need to:

1. Have examples that anyone can run anywhere. This means that our default should probably still be the mock catalogs. It doesn't really matter what data we use as long as someone opens the notebook can understand how to use the code from it.
2. Have a sub-directory for DC2 examples. These can still be around because they are helpful, but you can only run them if you are somewhere with the GCR reader installed and has local access to the DC2 data.

Just posting this to keep people in the loop and for additional thoughts. I can make the changes as they will only take a couple of minutes.

**Comment by matthewkirby** [comment]
Before I accept a review on this PR we should ensure that all of the demo notebook work. I cannot run them from my laptop so someone with NERSC access should do this. @marina-ricci @combet ?

- [ ] examples/DC2_examples/data_and_model_demo_DC2.ipynb runs
- [ ] examples/DC2_examples/shear_azimuthal_Averager_demo_DC2.ipynb
- [ ] examples/generate_mock_data.ipynb

I had some other comments but I think they are more involved so I am just going to open a new issue.

**Comment by combet** [comment]
Just checked things at NERSC and the example notebooks still work fine.

**Comment by matthewkirby** [comment]
@combet did you only check the two DC2 examples in this branch? When I run`generate_mock_data.ipynb` I am getting an error on the 4th cell when I run locally.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-c93281aa4324> in <module>()
----> 1 ideal_data.generate()
      2 noisy_data.generate(is_shapenoise=True, shapenoise=0.005, is_zerr=True)
      3 noisy_data_z.generate(is_shapenoise=True, is_zdistribution=True, is_zerr=True)

~/anaconda3/lib/python3.6/site-packages/clmm/mock_data.py in generate(self, is_shapenoise, shapenoise, is_zerr, sigma_z_ref, is_zdistribution, z_min, z_max, alpha, beta, z0)
    154 
    155         testProf = clmm_mod.nfwProfile(M = M, c = c, zL = zL, mdef = mdef, \
--> 156                                 chooseCosmology = self.config['cosmo'], esp = None)
    157 
    158         x_mpc = np.random.uniform(-4, 4, size=ngals)

~/anaconda3/lib/python3.6/site-packages/clmm/models/CLMM_densityModels_beforeConvertFromPerH.py in __init__(self, M, c, zL, mdef, chooseCosmology, esp)
    231     ##### We're going to swap out ``profile'' with ``Profile1D''
    232     def __init__(self, M , c , zL, mdef, chooseCosmology, esp = None):
--> 233         profile.__init__(self, zL, mdef, chooseCosmology)
    234 
    235         #self.parameters = parameters

~/anaconda3/lib/python3.6/site-packages/clmm/models/CLMM_densityModels_beforeConvertFromPerH.py in __init__(self, zL, mdef, chooseCosmology)
     77         self.zL = zL
     78         self.mdef = mdef
---> 79         self.G, self.v_c, self.H2, self.cosmo = self.calcConstants()
     80         return
     81 

AttributeError: 'nfwProfile' object has no attribute 'calcConstants'
```

**Comment by matthewkirby** [comment]
Disregard my last post. I had 5 different versions of clmm installed....

**Pull request merged**
