### PR TITLE
Solved issue 129. The last cell must be checked.

### PR DESCRIPTION
**Pull request by eduardojsbarroso**
The parameters of the last cell must be checked.

### CODE REVIEW

**Comment by hsinfan1996** [comment]
I took a look at the last cell and there is no error raised after I install this version of CLMM.

**Comment by marina-ricci** [comment]
Hi @eduardojsbarroso ! Thank you for your notebook.  I had a quick look and I have a couple of comments so far (I need to check more in depth) : 

- It is maybe worth to reduce the shape noise and/or the photo-z noise to better see the effect of miscentering 
- Could you indicate the offset distance in the legend and text instead of the coordinates of the centers? 
- Could you specify a radial binning to the `cl.make_radial_profile` function to have approximately the same binning for all the profiles?

**Comment by eduardojsbarroso** [comment]
Hi @marina-ricci. Thank you for the feedback. I will get started working on these points.

**Comment by marina-ricci** [comment]
@eduardojsbarroso you committed some changes to other notebooks. I think it was not intentional. Please reverse to the version in main by pulling and resolving the conflicts.

**Review by marina-ricci — CHANGES_REQUESTED** [review]
[ongoing] In addition to the above comments, please : 

- [x] correct typo in notebook name

**Comment by eduardojsbarroso** [comment]
@marina-ricci The fitter method was a lot better than the previous one, thank you for suggesting it. I believe to have covered the points that you mentioned. Sorry for the changes in the other notebooks, the nersc does it automatically whenever I open them and I forgot to restore.

**Comment by combet** [comment]
@eduardojsbarroso, @marina-ricci - thanks for the very nice new notebook. The only thing is that cell 7 raises an error at `hist = ax[1].hist(cl.galcat['z'], bins=bin_edges)[0]` as `bin_edges` is not defined. For the purpose of this figure I think simply having `bins=20` or any number is sufficient. Unless, you want something more specific here? 

I can make the small change myself if you wish, before approving the PR.

**Comment by marina-ricci** [comment]
> @eduardojsbarroso, @marina-ricci - thanks for the very nice new notebook. The only thing is that cell 7 raises an error at `hist = ax[1].hist(cl.galcat['z'], bins=bin_edges)[0]` as `bin_edges` is not defined. For the purpose of this figure I think simply having `bins=20` or any number is sufficient. Unless, you want something more specific here?
> 
> I can make the small change myself if you wish, before approving the PR.

Yes, please do. It must be a residual from another code!

**Review by combet — APPROVED** [review]
All good - thank you!

**Comment by combet** [comment]
@marina-ricci - you still have a change request open for this PR, so it can't be merged until you approve again I think

**Review by marina-ricci — APPROVED** [review]

**Pull request merged**
