### PR TITLE
Issue/635/Modify coordinate system implementation

### PR DESCRIPTION
**Pull request by marina-ricci**
This PR aims at resolving issues explained in issue  #635.

Copied from the issue : 

These are my suggestions : 

- [x] add warning message when GalaxyCluster (or compute_tangential_xxx, see second point) object is initiated without specifying the coordinate system. Like "no coordinate system provided, taking euclidean as default"
- [x] put coordinate system as a keyword for `compute_tangential_and_cross_components`, from data_ops or as a GalaxyCluster method. Maybe not necessary to have it as a GalaxyCluster keyword because it may be confusing as it is not necessarily propagated. 
- [x] create a simple notebook to highlight this.

### CODE REVIEW

**Comment by m-aguena** [comment]
@caioolivv would you like to take a look at this issue?

**Comment by caioolivv** [comment]
Hi @m-aguena, yes! The last month has been a bit chaotic, but I'll start working on this this week.

**Comment by caioolivv** [comment]
There's another unnoticed bug: calling `compute_tangential_and_cross_components()` repeatedly flips the sign of `e2` when it should stay the same.

**Comment by caioolivv** [comment]
Hi @marina-ricci and @ts485 ! In the demo notebook, there still seems to be a problem in DC2. Is that the same problem you've noticed?

**Comment by tomomis86** [comment]
Hi @caioolivv ,

Was your problem the path to the data directory or something else? If the latter, could you tell me what the problem is? My problem is simply that Cluster-related stages in TXPipe does not run with DC2 anymore.

**Comment by caioolivv** [comment]
> Hi @caioolivv ,
> 
> Was your problem the path to the data directory or something else? If the latter, could you tell me what the problem is? My problem is simply that Cluster-related stages in TXPipe does not run with DC2 anymore.

The problem is in the profile: neither coordinate system creates a profile with a lensing signal.

**Pull request closed without merging**
