### PR TITLE
Issue/455/add warnings

### PR DESCRIPTION
**Pull request by hsinfan1996**

### CODE REVIEW

**Comment by hsinfan1996** [comment]
Does anyone also encounter `AttributeError: 'NumCosmoCosmology' object has no attribute 'smd'` when calling `eval_sigma_crit` with NumCosmo backend?

**Comment by hsinfan1996** [comment]
@m-aguena @marina-ricci Can I fix issue #508 in this PR? I just need to delete a pair of quotation marks, so I do not want to create a branch for it.

**Comment by m-aguena** [comment]
> @m-aguena @marina-ricci Can I fix issue #508 in this PR? I just need to delete a pair of quotation marks, so I do not want to create a branch for it.

sure, go for it

**Comment by hsinfan1996** [comment]
I added a flag `show_warning=True` to `eval_critical_surface_density` and `eval_sigma_crit` to suppress the extra warnings. Not sure if there is better way to deal with that.

**Comment by hsinfan1996** [comment]
Merged to PR #512

**Pull request closed without merging**
