### PR TITLE
Clean notebook folder + additions to online documentation

### PR DESCRIPTION
**Pull request by combet**
- [x] Remove obsolete notebooks
- [x] Move NumCosmo comparison notebook to NC folder
- [x] Find better titles for the NB to make things clearer in the documentation
- [x] Add Example3 and Example2_NC to the online documentation

See the results by running `./update_docs` and opening `docs/_build/html/index.html` in your browser

### CODE REVIEW

**Comment by hsinfan1996** [comment]
In CONTRIBUTING.md, `source activate clmmenv` may not work if there is not any anaconda virtual environment activated, but `conda activate clmmenv` always works.

**Comment by combet** [comment]
> In CONTRIBUTING.md, `source activate clmmenv` may not work if there is not any anaconda virtual environment activated, but `conda activate clmmenv` always works.

Hmmm, for me `conda activate` does not work at NERSC... Anyhow, CONTRIBUTING.md and README.md will be taken care of as part of #289. The focus of this issue is the notebooks examples that we want to have appearing in the online documentation. Should have specified it more clearly, sorry.

**Comment by hsinfan1996** [comment]
In 

> > In CONTRIBUTING.md, `source activate clmmenv` may not work if there is not any anaconda virtual environment activated, but `conda activate clmmenv` always works.
> 
> Hmmm, for me `conda activate` does not work at NERSC... Anyhow, CONTRIBUTING.md and README.md will be taken care of as part of #289. The focus of this issue is the notebooks examples that we want to have appearing in the online documentation. Should have specified it more clearly, sorry.

I see.

**Review by hsinfan1996 — COMMENTED** [review]
Do we need to clear the cell outputs for modeling_cmp_numcosmo.ipynb?

**Comment by combet** [comment]
> Do we need to clear the cell outputs for modeling_cmp_numcosmo.ipynb?

Yes and done.

**Review by hsinfan1996 — APPROVED** [review]

**Pull request merged**
