### PR TITLE
Issue/325/rename modeling functions

### PR DESCRIPTION
**Pull request by combet**
Homogenise the function/method names for the OO and functional interfaces of the theory module. Use decision made in #325.

### CODE REVIEW

**Review by m-aguena — CHANGES_REQUESTED** [review]
It all seems good, according to the plan. I just think it is missing the update on the pair `get_critical_surface_density, eval_sigma_crit`

**Comment by combet** [comment]
> It all seems good, according to the plan. I just think it is missing the update on the pair `get_critical_surface_density, eval_sigma_crit`

Done.

**Review by m-aguena — CHANGES_REQUESTED** [review]
There is only one more to go, this one we even missed listing on the issue:
`get_reduced_shear_from_convergence` in `clmm/theory/generic.py`

**Comment by combet** [comment]
> There is only one more to go, this one we even missed listing on the issue:
> `get_reduced_shear_from_convergence` in `clmm/theory/generic.py`

And done :)

**Review by m-aguena — APPROVED** [review]
Great! Thanks

**Comment by m-aguena** [comment]
I will merge this PR to move things along, and if we can open another isssue later if we still find the naming of something can be improved.

**Pull request merged**
