### PR TITLE
Issue/335/nb for paper1.0

### PR DESCRIPTION
**Pull request by combet**
This PR is to bring all the NB developed to make the figures of the v1.0 paper into the `master` branch.

### CODE REVIEW

**Comment by combet** [comment]
@m-aguena, I've after merging #384 into master, I've brought the new validation NB into the `examples/Paper_v1.0` folder of branch #335 where we can gather all the NB needed to make the figures in the paper. I suggest we make any further plot modification in here, until we (and IR) are happy with everything.

**Comment by m-aguena** [comment]
@combet :+1: great idea!

**Comment by m-aguena** [comment]
As discussed on April 30th telecon, we sould add a shaded region on the r<1e-2Mpc plots of the code comparison plots to comment on the paper v1.0.

**Comment by combet** [comment]
The `validation_tests` NB is updated with the optimised CCL integration, following IR for the v1.0 paper. I believe this is the last figure change we'll make for the paper and we should be able to merge that branch to master now, before tagging up v1.0.

**Comment by pennalima** [comment]
@combet,  I just made a small modification in Fig. 3 legend: removed the dots of the ana. and opt. abbreviations.

Everything is OK. If you agree with this, I can approve this PR.

**Review by pennalima — APPROVED** [review]

**Comment by m-aguena** [comment]
Will be re-opened to remove a (erroneous) direct commit in master.

**Pull request merged**
