### PR TITLE
Add computations without flat sky

### PR DESCRIPTION
**Pull request by m-aguena**
Computations for (theta, phi) without flatsky approximations. The notebook (Flat_sky_limitations.ipynb) shows a difference at 0.0001% level on the mass fitted (10,000 times smaller than the mass error).

### CODE REVIEW

**Comment by m-aguena** [comment]
The tests are crashing because we computed the values assuming flat sky approximations. We should either recompute the values in the tests, increase the allowed error or pass flat sky to the tests.

**Comment by combet** [comment]
Thanks @m-aguena - this looks good.

> The tests are crashing because we computed the values assuming flat sky approximations. We should either recompute the values in the tests, increase the allowed error or pass flat sky to the tests.

Given that the default is now `curve`, I'd be in favour of having that option tested at least minimally. I've tried increasing the tolerance by a factor ten, but it's still not enough for the tests to pass. So maybe a compromise would be to:
- use the `flat` option when the tests call `compute_tangential_and_cross_components`
- add a `test_compute_lensing_angles_ap` that tests the curve option and maybe compares to the flatsky results (with a loose tolerance, 1e-2 might be sufficient)

What do you think?

**Comment by m-aguena** [comment]
@combet I fixed the tests to use flat_sky and created issue #390 to implement tests of curve sky in the future.

**Review by combet — APPROVED** [review]
Thank you @m-aguena, all good!

**Pull request merged**
