### PR TITLE
Issue/249/dc2 notebooks

### PR DESCRIPTION
**Pull request by combet**
Here's what has been done:
- [x] `data_and_model_demo_DC2` notebook updated to work again with CLMM (some major refactoring occured at some point last year and it was not working anymore). This works with cosmoDC2.
- [x] New notebook `DC2_gt_profiles` exemplifies the usage of both the cosmoDC2 and the DC2 object catalog to build reduced tangential shear profiles using CLMM. It also shows how to match the two catalogs of background galaxies and how to account for shape noise in cosmoDC2. (Largely inspired from the DC2 tutorial notebooks, but with a focus on clusters).
- [x] The old `shear_azimuthal_Averager_demo_DC2` notebook was deleted as it was superseeded by `data_and_model_demo_DC2` a while back.

To test those notebooks, you need to have a NERSC environnement setup with both CLMM and GCRCatalogs. Follow the instructions from [CONTRIBUTING](https://github.com/LSSTDESC/CLMM/blob/issue/250/instructions_dc2_nersc/CONTRIBUTING.md) in branch #250 to check if this works. Also making a PR for #250.

### CODE REVIEW

**Comment by marina-ricci** [comment]
This is really nice and thorough @combet ! Both notebooks work at CC with the `desc` environment + CLMM and cluster_toolkit. The notebook `data_and_model_demo_DC2.ipynb` is very clear and consize. The notebook `DC2_gt_profiles.ipynb` is much longer and technical. It is very interesting as it allows to see how to use CLMM with different type of inputs but is is quite heavy to follow and require a good knowledge of the DC2 data products. I suggest that someone less aquainted with DC2 should try it to see if it is understandable. The access at NERS has also to be tested.

**Comment by combet** [comment]
Thank you @marina-ricci for the detailed reviews of both notebook. All you points have been addressed. In particular:
- Please note the new small section in `data_and_model_demo_DC2` addressing the units of `halo_mass` and possible sources of confusion.
- As per your suggestion, I moved the function computing lensed ellipticities into `utils.py`. It's now fully documented. I've also added a minimal validation test for that function in `test_utils.py`.
- I agree that the `DC2_gt_profile` notebook is quite technical. Someone with less DC2 experience than you should look at it (and at NERSC).

**Comment by marina-ricci** [comment]
All my previous comments have been addressed, from my point of view this PR can be merged.

**Comment by cavestruz** [comment]
Need to make changes friendly with #276 before merging this (e.g. GCData object)

**Comment by combet** [comment]
Changes to accomodate #276 have been made to both notebooks. Can be merged once runability at NERSC in confirmed by @cavestruz and @pennalima.

**Comment by pennalima** [comment]
Hi @combet ,

Notebook "data_and_model..." runs is NERSC! 

Notebook DC2_gt_profiles.ipynb: 
We need to include the following requirements in CONTRIBUTING.md
pip install pandas
pip install pyarrow
pip install healpy

The notebook runs including installing these requirements.

More comments:
Once the environment is activated, I think we should standardized the setup.py installation ALWAYS using --user or NEVER using it. For example, as described in CONTRIBUTING.md, the clustertoolkit installation is indicated without --user, while the clmm has it. 
In NERSC this can be a "problem" since you can end up installing packages in two different 
places.
I just did that. When I installed clmm from the right branch I did not used "--user", but I have used it in my first installation. This takes precedence over installations without it (--user). I was getting the other branch installation without knowing it.    

I found the following warnings running the notebook: 

/global/homes/m/mpenna/.conda/envs/clmmenv/lib/python3.8/site-packages/GCRCatalogs/dc2_dm_catalog.py:43: RuntimeWarning: divide by zero encountered in log10
  return -2.5 * np.log10(flux) + AB_mag_zp_wrt_nanoJansky
/global/homes/m/mpenna/.conda/envs/clmmenv/lib/python3.8/site-packages/GCRCatalogs/dc2_dm_catalog.py:43: RuntimeWarning: invalid value encountered in log10
  return -2.5 * np.log10(flux) + AB_mag_zp_wrt_nanoJansky

/global/homes/m/mpenna/.local/cori/3.7-anaconda-2019.10/lib/python3.8/site-packages/clmm-0.3.0-py3.8.egg/clmm/utils.py:229: RuntimeWarning: invalid value encountered in sqrt

We should check this last one.

**Comment by combet** [comment]
Thanks @pennalima for identifying the missing imports. They all have to do with either GCR, GCRCatalogs or FoFMatching. I've updated CONTRIBUTING in branch `issue/250/...` to reflect those changes. I also remove the `--user` flag - with the user working from their own conda environment, there's no need for it.

**Comment by combet** [comment]
The `RuntimeWarning: invalid value encountered in sqrt` you saw comes from `convert_shapes_to_epsilon` in `utils.py`. It's due to some values of the shape components in the DC2 object catalog. I think relying on this `RuntimeWarning` is sufficient.

**Comment by combet** [comment]
Before merging, need to change the names of the functions in the notebooks to reflect the new name scheme that has just been merged (PR #283) !! Will do that asap and merge once done.

**Pull request merged**
