### PR TITLE
re add plotting to galaxycluster

### PR DESCRIPTION
**Pull request by m-aguena**
Add plot_profiles back to `GalaxyCluster`. Main function was separated from `GalaxyCluster` calling.

### CODE REVIEW

**Review by combet — CHANGES_REQUESTED** [review]
Thanks @m-aguena, this looks good! The last thing to change is to update the `demo_dataops` notebook to use the new syntax. For example,
`fig, ax = plot_profiles(cl,xscale='log')` does not work anymore and should be changed throughout as
`fig, ax = cl.plot_profiles(xscale='log')`

**Comment by combet** [comment]
Another thing I noticed. If we try to reproduce the last figure of the `demo_dataops` notebook, using the plot_profile method as
`cl.plot_profiles(tangential_component='DeltaSigma_tan',
    tangential_component_error='DeltaSigma_tan_err',
    cross_component='DeltaSigma_cross',
    cross_component_error='DeltaSigma_cross_err',
    table_name='DeltaSigma_profile',
    xscale='linear',
    yscale='linear')`  

the figure looks OK but the x and y titles are not updated (ylabel is still $\gamma$, suggestiing shear while we're plotting the DeltaSigma). Should we make the axes names simply be the Table column names?

**Comment by m-aguena** [comment]
> Thanks @m-aguena, this looks good! The last thing to change is to update the `demo_dataops` notebook to use the new syntax. For example,
> `fig, ax = plot_profiles(cl,xscale='log')` does not work anymore and should be changed throughout as
> `fig, ax = cl.plot_profiles(xscale='log')`

Done!

**Comment by m-aguena** [comment]
> Another thing I noticed. If we try to reproduce the last figure of the `demo_dataops` notebook, using the `plot_profile` method as
> `cl.plot_profiles(tangential_component='DeltaSigma_tan', tangential_component_error='DeltaSigma_tan_err', cross_component='DeltaSigma_cross', cross_component_error='DeltaSigma_cross_err', table_name='DeltaSigma_profile', xscale='linear', yscale='linear')`
> 
> the figure looks OK but the x and y titles are not updated (ylabel is still $\gamma$, suggestiing shear while we're plotting the DeltaSigma). Should we make the axes names simply be the Table column names?

Done as well!

**Comment by m-aguena** [comment]
Naming of modules will be sorted on #348

**Review by combet — APPROVED** [review]
All good. Thanks a lot @m-aguena!

**Pull request merged**
